name: sky_cast_weather
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.6.1
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  intl: ^0.18.1
  flutter_animate: ^4.5.2
  equatable: ^2.0.7
  flutter_typeahead: ^5.2.0
  cached_network_image: ^3.4.1
  lottie: ^3.3.1
  permission_handler: ^11.3.1
  envied: ^1.2.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  dio: ^5.9.0
  envied_generator: ^1.2.0
  build_runner: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/jsons/